name: Test

on:
  push:
    branches:
      - master
      - develop
      - context
  pull_request:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -coverprofile=coverage.out -covermode=atomic -v .

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --issues-exit-code=0
        skip-go-installation: true

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
